Portfolio: setup
Hisoka37/My-Portfolio pull request #1
Opened 2023-01-11 16:15 UTC by Hisoka37

2023-01-11 18:44 UTC, MeqdamAlqudah requested changes
Hi @Hisoka37 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

![](https://media0.giphy.com/media/YT95XJOLvY1t2SJgpR/200w.webp?cid=ecf05e47yl4lgszqh7mcg0wss9z18wpwfp21v3rjlnx7gj8w&rid=200w.webp&ct=g)

 ## Highlights

:+1: Readme file
:+1: Pull request description.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-11 18:44 UTC, MeqdamAlqudah commented on index.html
> +      </nav>
- [ ] Please the container of the Toolbar section should be a `header` tag as it is semantically better while the hamburger button only should be wrapped in a nav tag.

2023-01-11 18:44 UTC, MeqdamAlqudah commented on index.html
> +        <img src="/assets/My Logo.svg" class="logo" />
- [ ] Please the logo should be a link to the home page, if you check websites like youtube and facebook you will notice that their logo sends the user to the home page.

2023-01-11 18:44 UTC, MeqdamAlqudah commented on index.html
> +        <div>
- [ ] Please your code should have margins (top, bottom, left, right) defined in the design, it is a really important skill to give the same design requested from you.

| Your code  | Figma|
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/74744787/211888648-01fb9d37-c7b0-40da-a8b2-97040fe910b7.png) | ![image](https://user-images.githubusercontent.com/74744787/211888440-f581d54e-5ba4-4472-bf19-1450152f720b.png)|

2023-01-11 18:44 UTC, MeqdamAlqudah commented on index.html
> +        </div>
- [ ] Please these icons form a list and should be wrapped in a `ul` tag with `li` elements this is semantically better.

2023-01-11 18:44 UTC, MeqdamAlqudah commented on index.html
> +          <a href=""><img src="/assets/Github.svg" alt="Github" /></a>
- [ ] Please Headline section should  has the margins (top, bottom, left, right) defined in the design

| Your code  | Figma code |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/74744787/211890782-2598ac66-43ef-42da-ab6f-cda252c10a39.png)  | ![image](https://user-images.githubusercontent.com/74744787/211890999-3269efaa-b77c-4119-af6f-4b8255dbdc07.png)  |

2023-01-12 10:59 UTC, nedjwab approved these changes
# 🟢 Project Approved! 🏆

## Hi @Hisoka37  👋

Your project is complete! ✔️ 🏁

Your code was very professional 💯

There is nothing else to say other than... _it's time to merge it_ :shipit:
Congratulations! 🎉

 
## Highlights 🌟

- ✔️ Descriptive commmit messsages
- ✔️ Descriptive PR description
- ✔️ No linter Errors
- The code is top-notch! 💯 and have a huge potential.

Cheers and Happy coding!👏👏👏

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.


_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-12 11:15 UTC, merged